title: Harmony In Diversity Gallery
url: https://www.harmonyindiversitygallery.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#333333"
  secondary-color: "#4372d6"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#bd9cc7"
    - title: media-color-three
      color: "#f680a3"
    - title: media-color-four
      color: "#7fd2f0"
    - title: media-color-five
      color: "#a6d994"
description: The Harmony in Diversity Gallery (HDG) was developed by the
  Ministry of Home Affairs in collaboration with community partners and
  organisations. The Gallery aims to promote an appreciation of Singapore's rich
  religious diversity. It hopes this will foster a spirit of give and take,
  mutual respect and understanding, necessary to nurture and strengthen the
  religious peace and harmony we enjoy today.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1m2m2z1g84ttq.amplifyapp.com
prod: https://master.d1m2m2z1g84ttq.amplifyapp.com
shareicon: /images/masthead_logo_270.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
